"""From numeric to float

Revision ID: 1ecb5dd70cbb
Revises: 0009c9dfa885
Create Date: 2025-08-13 13:38:42.552199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecb5dd70cbb'
down_revision: Union[str, Sequence[str], None] = '0009c9dfa885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invsetingapibot_portfolios', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=38, scale=18),
               existing_nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invsetingapibot_portfolios', schema=None) as batch_op:
        batch_op.alter_column('buy_price',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=38, scale=18),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)

    # ### end Alembic commands ###
