"""Deleted id columns

Revision ID: 3cf11a2d7524
Revises: 3f6bec9ea6f5
Create Date: 2025-08-10 20:04:42.399738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf11a2d7524'
down_revision: Union[str, Sequence[str], None] = '3f6bec9ea6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invsetingapibot_portfolios', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('invsetingapibot_users', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invsetingapibot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(), nullable=False))
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('invsetingapibot_portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
