"""Added direction to Alerts

Revision ID: c025d42d80ef
Revises: 06da30158213
Create Date: 2025-08-18 12:25:19.705996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c025d42d80ef'
down_revision: Union[str, Sequence[str], None] = '06da30158213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investingapibot_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investingapibot_alerts', schema=None) as batch_op:
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
