"""Portofolio table added

Revision ID: eeb9e503ae67
Revises: 0a05388581a2
Create Date: 2025-08-10 15:43:01.844872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb9e503ae67'
down_revision: Union[str, Sequence[str], None] = '0a05388581a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invsetingapibot_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['invsetingapibot_users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invsetingapibot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invsetingapibot_users', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('id')

    op.drop_table('invsetingapibot_portfolios')
    # ### end Alembic commands ###
